In [55]:
from __future__ import print_function, division
import os
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, utils
import random

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

In [155]:
test = pd.read_csv("train.csv")

In [302]:
class ToTensor(object):
    
    def __call__(self, sample):
        
        tensor = torch.from_numpy(np.array(sample["image"]/255).astype(np.float32))
        target = torch.from_numpy(np.array(sample["target"]).astype(np.float32))
        
        return {"target":target, "image":tensor}

class mnist_dataset(Dataset):
    
    def __init__(self, csv_file, transform = None):
        
        df = pd.read_csv(csv_file)
        self.target = pd.get_dummies(test["label"]).values
        self.variable = df.drop(columns=["label"]).values
        self.transform = transform
        
    def __len__(self):
        return len(self.target)
    
    def __getitem__(self, idx):
        
        sample = {'target':self.target[idx],'image':self.variable[idx]}
        
        if self.transform:
            sample = self.transform(sample)
            
        return sample

In [303]:
#load dataset
mnist_df = mnist_dataset("train.csv")

#plot some images
fig = plt.figure(figsize=(14,5))
for i in range(1,11):
    plt.subplot(2,5,i)
    idx = random.randint(0, len(mnist_df)-1)
    plt.imshow(mnist_df[idx]["image"].reshape(28,28))

plt.show()

In [700]:
# 1 layer Neural Network

batch_size = 32
input_size = len(mnist_df[0]["image"])
output_layer_size = len(mnist_df[0]["target"])
hidden_layer_size = 100

mnist_df = mnist_dataset("train.csv", transform = (ToTensor()))
dataset_loader = torch.utils.data.DataLoader(mnist_df, batch_size=batch_size, shuffle=True)

#intialize weights
w1 = torch.randn(input_size, hidden_layer_size, dtype = torch.float)
b1 = torch.randn(hidden_layer_size)
w2 = torch.randn(hidden_layer_size, output_layer_size, dtype = torch.float)
b2 = torch.zeros(output_layer_size)

learning_rate = 1e-6

In [ ]:

for i in range(400):
    for idx, batch in enumerate(dataset_loader, 1):

        X = batch["image"]
        Y = batch["target"]

        #forward propagation
        Z1 = X.mm(w1) + b1
        X2 = Z1.tanh()
        Z2 = X2.mm(w2) + b2
        A = torch.sigmoid(z2)




        #backward propagation
        dZ2 = A - Y
        dW2 = dZ2.t().mm(X2).t() * 1/m
        db2 = torch.sum(dZ2, dim=0)
        dZ1 = torch.mul(dZ2.mm(w2.t()), 1-X2.pow(2))
        dW1 = X.t().mm(dZ1) * 1/m
        db1 = dZ1.sum(dim=0)
        
        w1 = w1 - learning_rate * dW1
        b1 = b1 - learning_rate * db1
        w2 = w2 - learning_rate * dW2
        b2 = b2 - learning_rate * db2
        
    #Cost / Loss
    cost = (torch.sum(torch.mul(torch.log(A), Y) + torch.mul((1-Y), torch.log(1-A))) ) / len(A)
    print("iteration: {}, cost:{}".format(i, cost))

iteration: 0, cost:-384.6148681640625
iteration: 1, cost:-350.4373779296875
iteration: 2, cost:-357.7351989746094
iteration: 3, cost:-323.8299255371094
iteration: 4, cost:-350.21905517578125
iteration: 5, cost:-397.6826171875
iteration: 6, cost:-393.8050842285156
iteration: 7, cost:-442.5880432128906


In [695]:
X.t().mm(torch.mul(dZ2.mm(w2.t()), 1-X2.pow(2))).size()

torch.Size([784, 100])

In [670]:
x = mnist_df[0]["image"]

In [309]:
Y = mnist_df[0]["target"]

In [514]:
# forward propagation
z1 = x.mm(w1) + b1
x2 = z1.tanh()
z2 = x2.mm(w2) + b2
A = torch.sigmoid(z2)

# backward propagation

dZ2 = A - Y
dW2 = dZ2.t().mm(x2).t() * 1/m
db2 = torch.sum(dZ2, dim=0)
dZ1 = torch.mul(dZ2.mm(w2.t()), 1-z1.pow(2))
dW1 = x.t().mm(dZ1) * 1/m
db1 = dZ1.sum(dim=0)

In [342]:
cost = (torch.sum(torch.mul(torch.log(A), Y) + torch.mul((1-Y), torch.log(1-A))) ) / len(A)

In [ ]:
    dZ1 = np.multiply(np.dot(W2.T, dZ2), 1 - np.power(A1, 2))
    dW1 = (1 / m) * np.dot(dZ1, X.T)
    db1 = (1 / m) * np.sum(dZ1, axis=1, keepdims=True)

In [643]:
z1.size(Z)

torch.Size([1, 100])

In [649]:
.size()

torch.Size([1, 100])

In [660]:
w1.size()

torch.Size([784, 100])

In [661]:
dZ1.size()

torch.Size([1, 100])

In [579]:
g=dZ2.t().mm(x2).t()

In [570]:
g=g.transpose()

In [582]:
w2 - g

tensor([[-0.7607,  2.9369,  0.5967, -0.0079, -1.4002,  0.0081, -0.9959, -0.3968,
         -1.5415, -0.9113],
        [-0.0557, -1.2771,  1.7322, -0.4332,  0.3828,  0.7154, -0.0916,  1.1509,
         -0.1248,  0.1637],
        [-0.4942,  2.7576, -0.5755, -0.6501, -0.8592, -1.0933,  1.8032, -2.3724,
         -1.1119,  0.2740],
        [-0.6346,  0.5143,  0.7830, -1.1630,  0.5640, -0.8237, -1.2244,  0.5636,
          0.0202,  0.1795],
        [ 1.0715, -0.7036,  0.6225,  0.3146,  0.6557, -0.6905,  1.0418,  0.4318,
          0.4224, -0.6583],
        [-1.1561,  1.8455,  0.1888, -0.2077,  0.9009, -0.7983, -1.5306, -0.7259,
          1.0418, -0.9802],
        [-0.9347,  0.2285,  0.3882,  1.2153, -0.5829,  2.3629,  1.7447, -0.1498,
          0.5409, -0.8059],
        [ 1.4517,  0.6645,  0.4231, -1.1929, -0.0321, -0.1120, -0.3116, -0.9900,
         -1.3029, -1.0502],
        [ 0.2264,  1.6344, -0.7792,  0.0116, -2.0122,  1.0926, -1.7063, -2.5952,
         -0.5151,  0.4394],
        [ 0.0440, -

In [528]:
grad_input = np.dot(dZ2,w2.t())

In [541]:
w1 - dZ2.t().mm(A)

RuntimeError: The size of tensor a (100) must match the size of tensor b (10) at non-singleton dimension 1

In [ ]:
  def backward(self,input,grad_output):
        # compute d f / d x = d f / d dense * d dense / d x
        # where d dense/ d x = weights transposed
        grad_input = np.dot(grad_output,np.transpose(self.weights))

        # compute gradient w.r.t. weights and biases
        grad_weights = np.transpose(np.dot(np.transpose(grad_output),input))
        grad_biases = np.sum(grad_output, axis = 0)
        
        # Here we perform a stochastic gradient descent step. 
        # Later on, you can try replacing that with something better.
        self.weights = self.weights - self.learning_rate * grad_weights
        self.biases = self.biases - self.learning_rate * grad_biases
        return grad_input

In [354]:
    # Compute and print loss
    loss = (y_pred - y).pow(2).sum().item()
    print(t, loss)

    # Backprop to compute gradients of w1 and w2 with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.t().mm(grad_y_pred)
    grad_h_relu = grad_y_pred.mm(w2.t())
    grad_h = grad_h_relu.clone()
    grad_h[h < 0] = 0
    grad_w1 = x.t().mm(grad_h)


AttributeError: 'Tensor' object has no attribute 'Transpose'

In [ ]:
        grad_weights = np.transpose(np.dot(np.transpose(grad_output),input))
        grad_biases = np.sum(grad_output, axis = 0)

In [492]:
w2.size()

torch.Size([100, 10])

In [594]:
dZ2

tensor([[ 5.0084e-04, -9.8701e-01,  5.6031e-03,  1.9205e-05,  1.0389e-06,
          1.0000e+00,  3.7445e-01,  9.8186e-01,  8.1262e-01,  8.7171e-10]])

In [604]:
 * 1/m

tensor([ 5.0084e-05, -9.8701e-02,  5.6031e-04,  1.9205e-06,  1.0389e-07,
         1.0000e-01,  3.7445e-02,  9.8186e-02,  8.1262e-02,  8.7171e-11])

In [474]:
dZ2 = A - Y
dW2 = torch.dot(dZ2, A.t()) * 1/m
db2 = (1 / m) * dZ2.sum()
dZ1 = 

RuntimeError: dot: Expected 1-D argument self, but got 2-D

In [365]:
db2 = torch.sum(dZ2) * 1/m

In [387]:
dZ2.dot(w2.t()).size()

RuntimeError: dot: Expected 1-D argument self, but got 2-D

In [395]:
np.multiply(np.dot(dZ2, w2.t()), A.t())

torch.Size([10, 100])

In [380]:
dZ2.size()

torch.Size([1, 10])

In [383]:
w2.size()

torch.Size([100, 10])

In [384]:
dZ2.dot()

RuntimeError: dot: Expected 1-D argument self, but got 2-D

In [411]:
dZ2.size()

torch.Size([1, 10])

RuntimeError: size mismatch, m1: [10 x 100], m2: [1 x 10] at c:\a\w\1\s\tmp_conda_3.7_104535\conda\conda-bld\pytorch_1550400486030\work\aten\src\th\generic/THTensorMath.cpp:940

tensor([[1.0000e+00, 9.9983e-01, 9.9997e-01, 1.0000e+00, 1.0000e+00, 5.0068e-06,
         8.5979e-01, 3.5942e-02, 3.3965e-01, 1.0000e+00]])

In [465]:
np.multiply(np.dot(dZ2, w2.t()), 1 - np.power(A, 2))

ValueError: operands could not be broadcast together with shapes (1,100) (1,10) 

In [470]:
np.dot(w2.t(), dZ2)

ValueError: shapes (10,100) and (1,10) not aligned: 100 (dim 1) != 1 (dim 0)

In [457]:
g.size()

torch.Size([10, 100])

In [449]:
x.t().size()

torch.Size([784, 1])

In [441]:
np.dot()

torch.Size([784, 100])

In [429]:
w2.t().mm(dZ2)

RuntimeError: size mismatch, m1: [10 x 100], m2: [1 x 10] at c:\a\w\1\s\tmp_conda_3.7_104535\conda\conda-bld\pytorch_1550400486030\work\aten\src\th\generic/THTensorMath.cpp:940

In [ ]:
dZ2 = A - Y
dW2 = (1/len(A)) * torch.mm(dZ2, torch.tr)
    
    
    dZ2 = A2 - Y
    dW2 = (1 / m) * np.dot(dZ2, A1.T)
    db2 = (1 / m) * np.sum(dZ2, axis=1, keepdims=True)
    dZ1 = np.multiply(np.dot(W2.T, dZ2), 1 - np.power(A1, 2))
    dW1 = (1 / m) * np.dot(dZ1, X.T)
    db1 = (1 / m) * np.sum(dZ1, axis=1, keepdims=True)

In [ ]:
#
logprobs = np.multiply(np.log(A2), Y) + np.multiply((1 - Y), np.log(1 - A2)
cost = - np.sum(logprobs) / m

In [293]:
    W1 = W1 - learning_rate * dW1
    b1 = b1 - learning_rate * db1
    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2

tensor([[9.7142e-01, 9.8408e-01, 4.4570e-01, 1.1091e-02, 9.9317e-01, 4.5503e-01,
         4.1570e-05, 2.2966e-06, 9.4397e-01, 9.9969e-01]])

In [269]:
x.dtype

dtype('int64')

In [194]:
import torch.nn.functional as F
y_pred = F.relu(x.mm(w1)).mm(w2)

In [195]:
w1 +

torch.Size([784, 100])

In [69]:

device = torch.device("cpu")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

# Randomly initialize weights
w1 = torch.randn(D_in, H, device=device, dtype=dtype)
w2 = torch.randn(H, D_out, device=device, dtype=dtype)

learning_rate = 1e-6
for t in range(500):
    # Forward pass: compute predicted y
    h = x.mm(w1)
    h_relu = h.clamp(min=0)
    y_pred = h_relu.mm(w2)

    # Compute and print loss
    loss = (y_pred - y).pow(2).sum().item()
    print(t, loss)

    # Backprop to compute gradients of w1 and w2 with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.t().mm(grad_y_pred)
    grad_h_relu = grad_y_pred.mm(w2.t())
    grad_h = grad_h_relu.clone()
    grad_h[h < 0] = 0
    grad_w1 = x.t().mm(grad_h)

    # Update weights using gradient descent
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0 34189644.0
1 29711042.0
2 25080740.0
3 18660142.0
4 12330950.0
5 7497069.0
6 4546526.0
7 2902201.25
8 2006440.75
9 1492909.875
10 1173900.875
11 957528.6875
12 799244.8125
13 677228.875
14 579924.8125
15 500347.90625
16 434364.65625
17 379013.25
18 332180.4375
19 292356.6875
20 258268.796875
21 228920.875
22 203582.75
23 181601.8125
24 162425.640625
25 145649.0625
26 130930.4453125
27 117981.171875
28 106551.515625
29 96440.2890625
30 87453.6875
31 79450.4375
32 72303.5390625
33 65906.796875
34 60172.09375
35 55019.1796875
36 50379.0234375
37 46193.25
38 42412.546875
39 38990.953125
40 35888.5859375
41 33071.70703125
42 30509.693359375
43 28177.359375
44 26056.974609375
45 24121.87109375
46 22351.509765625
47 20729.916015625
48 19243.84765625
49 17879.345703125
50 16626.712890625
51 15475.47265625
52 14414.658203125
53 13436.5048828125
54 12533.4931640625
55 11699.3125
56 10928.251953125
57 10214.3896484375
58 9553.46875
59 8940.7294921875
60 8371.9814453125
61 7843.9423828125
62 735

In [ ]:
# -*- coding: utf-8 -*-
import torch


class TwoLayerNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        """
        In the constructor we instantiate two nn.Linear modules and assign them as
        member variables.
        """
        super(TwoLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H)
        self.linear2 = torch.nn.Linear(H, D_out)

    def forward(self, x):
        """
        In the forward function we accept a Tensor of input data and we must return
        a Tensor of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Tensors.
        """
        h_relu = self.linear1(x).clamp(min=0)
        y_pred = self.linear2(h_relu)
        return y_pred


# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# Construct our model by instantiating the class defined above
model = TwoLayerNet(D_in, H, D_out)

# Construct our loss function and an Optimizer. The call to model.parameters()
# in the SGD constructor will contain the learnable parameters of the two
# nn.Linear modules which are members of the model.
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-4)
for t in range(500):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    print(t, loss.item())

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()